<?php

declare(strict_types=1);

// ============================================================================
// AUTO-GENERATED BY AOP ENGINE — DO NOT EDIT
// ============================================================================
//
// This file shows what the AopProxyGeneratorCompiler produces for
// OriginalService. You NEVER write this code — it's generated
// automatically when you run `php artisan di:compile`.
//
// Real generated proxies live in: storage/framework/aop/
// This file is here for educational purposes only.
//
// Generated from: Pixielity\Aop\Examples\ProxyGeneration\OriginalService
// Generated at:   2026-04-12T00:00:00+00:00
//
// ============================================================================

namespace Pixielity\Aop\Generated;

use Pixielity\Aop\Engine\InterceptorEngine;
use Pixielity\Aop\Examples\ProxyGeneration\OriginalService;

/**
 * AOP Proxy for OriginalService.
 *
 * This class EXTENDS the original — so instanceof checks still work:
 *
 *   $service = app(OriginalService::class);
 *   $service instanceof OriginalService; // true ✅
 *
 * ## What this proxy does:
 *
 *   1. Overrides ONLY intercepted methods (findBySlug, createProduct, deleteProduct)
 *   2. Non-intercepted methods (getStats) are NOT overridden — they fall
 *      through to the parent class with zero overhead
 *   3. Each overridden method delegates to InterceptorEngine::execute()
 *   4. The engine builds a pipeline of interceptors and executes them
 *   5. The last step in the pipeline calls parent::methodName() — the
 *      original implementation
 *
 * ## How the container swap works:
 *
 *   AopServiceProvider::boot() registers:
 *     $this->app->bind(OriginalService::class, fn ($app) => $app->make(
 *         Pixielity\Aop\Generated\Pixielity_Aop_Examples_ProxyGeneration_OriginalService::class
 *     ));
 *
 *   So when any code does:
 *     $service = app(OriginalService::class);
 *
 *   The container returns THIS proxy class instead of the original.
 *
 * @internal Auto-generated. Do not modify.
 */
class Pixielity_Aop_Examples_ProxyGeneration_OriginalService extends OriginalService
{
    // =========================================================================
    // findBySlug — Intercepted by CacheInterceptor
    // =========================================================================

    /**
     * Proxy override for findBySlug().
     *
     * Instead of executing the original method directly, this delegates
     * to InterceptorEngine::execute() which:
     *
     *   1. Looks up interceptors for OriginalService::findBySlug
     *      → finds [CacheInterceptor (priority: 100)]
     *   2. Builds a Pipeline with CacheInterceptor as a stage
     *   3. Executes the pipeline:
     *      CacheInterceptor.handle($this, 'findBySlug', $args, $next)
     *        → $next() calls the $original closure below
     *        → $original calls parent::findBySlug($slug)
     *   4. Returns the result (cached or fresh)
     *
     * @param  string  $slug  The product slug.
     * @return object|null The product or null.
     */
    public function findBySlug(string $slug): ?object
    {
        // Resolve the InterceptorEngine from the container (singleton)
        return app(InterceptorEngine::class)->execute(
            // $target: the proxy instance (which extends OriginalService)
            target: $this,

            // $method: the method name being intercepted
            method: 'findBySlug',

            // $args: the method arguments as a positional array
            // The engine enriches this with '__parameters' from the attribute
            args: func_get_args(),

            // $original: closure that calls the PARENT (original) method
            // This is the last step in the pipeline — only called if all
            // interceptors call $next()
            original: function (string $slug): ?object {
                return parent::findBySlug($slug);
            },
        );
    }

    // =========================================================================
    // createProduct — Intercepted by TransactionInterceptor + AuditInterceptor
    // =========================================================================

    /**
     * Proxy override for createProduct().
     *
     * This method has TWO interceptors stacked:
     *   1. TransactionInterceptor (priority: 50) — outermost
     *   2. AuditInterceptor (priority: 100) — inner
     *
     * The engine sorts by priority and builds the pipeline:
     *
     *   TransactionInterceptor.handle()
     *     → DB::transaction(fn () => $next())
     *       → AuditInterceptor.handle()
     *         → $result = $next()
     *           → parent::createProduct($data)  ← original method
     *         → activity()->log('product.created')
     *         → return $result
     *     → DB::commit()
     *     → return $result
     *
     * @param  array<string, mixed>  $data  The product data.
     * @return object The created product.
     */
    public function createProduct(array $data): object
    {
        return app(InterceptorEngine::class)->execute(
            target: $this,
            method: 'createProduct',
            args: func_get_args(),
            original: function (array $data): object {
                return parent::createProduct($data);
            },
        );
    }

    // =========================================================================
    // deleteProduct — Intercepted by TransactionInterceptor + AuditInterceptor
    // =========================================================================

    /**
     * Proxy override for deleteProduct().
     *
     * Same pattern as createProduct — two interceptors stacked.
     *
     * @param  int  $id  The product ID.
     * @return bool True if deleted.
     */
    public function deleteProduct(int $id): bool
    {
        return app(InterceptorEngine::class)->execute(
            target: $this,
            method: 'deleteProduct',
            args: func_get_args(),
            original: function (int $id): bool {
                return parent::deleteProduct($id);
            },
        );
    }

    // =========================================================================
    // getStats — NOT overridden (no interceptors)
    // =========================================================================

    // getStats() is NOT listed here because it has no interceptor attributes.
    // When called, PHP's method resolution goes straight to the parent class
    // (OriginalService::getStats) with zero AOP overhead.
    //
    // This is why the proxy only overrides intercepted methods — non-intercepted
    // methods have zero performance cost.
}
