<?php

declare(strict_types=1);

/**
 * Scope Registry Compiler.
 *
 * Compiler pass that discovers all #[AsScope] attributes across the
 * application at build time, collects their scope key and description
 * pairs, and caches the complete registry to a PHP file for fast
 * runtime loading. Executed during the REGISTRY phase of compilation.
 *
 * The compiled cache file is stored at bootstrap/cache/scope_registry.php
 * and returns an associative array of scope keys to descriptions.
 *
 * @category Compiler
 *
 * @since    1.0.0
 *
 * @see \Pixielity\Developer\Attributes\AsScope
 * @see \Pixielity\Developer\Registry\ScopeRegistry
 * @see \Pixielity\Compiler\Contracts\CompilerInterface
 */

namespace Pixielity\Developer\Compiler;

use Pixielity\Compiler\Attributes\AsCompiler;
use Pixielity\Compiler\Contracts\CompilerContext;
use Pixielity\Compiler\Contracts\CompilerInterface;
use Pixielity\Compiler\Contracts\CompilerResult;
use Pixielity\Compiler\Enums\CompilerPhase;
use Pixielity\Developer\Attributes\AsScope;
use Pixielity\Developer\Registry\ScopeRegistry;
use Pixielity\Discovery\Facades\Discovery;

/**
 * Discovers #[AsScope] attributes and builds the scope registry cache.
 *
 * Scans all classes annotated with #[AsScope] via the Discovery facade,
 * extracts scope key-description pairs, writes them to a cached PHP file,
 * and populates the ScopeRegistry instance in the container.
 */
#[AsCompiler(priority: 35, phase: CompilerPhase::REGISTRY, description: 'Discover OAuth scopes and build scope registry')]
class ScopeRegistryCompiler implements CompilerInterface
{
    /**
     * The path to the compiled scope registry cache file.
     *
     * @var string
     */
    private const CACHE_PATH = 'bootstrap/cache/scope_registry.php';

    /**
     * {@inheritDoc}
     *
     * Discovers all #[AsScope] attributes, builds the scope map, writes
     * the cache file, and populates the ScopeRegistry in the container.
     * Each class may have multiple #[AsScope] attributes (repeatable).
     */
    public function compile(CompilerContext $context): CompilerResult
    {
        $discovered = Discovery::attribute(AsScope::class)->get();
        $scopes = [];

        $discovered->each(function (array $metadata, string $class) use (&$scopes, $context): void {
            $forClass = Discovery::forClass($class);

            foreach ($forClass->classAttributes as $attr) {
                if ($attr instanceof AsScope) {
                    $scopes[$attr->key] = $attr->description;

                    if ($context->verbose) {
                        $context->comment("  Scope: {$attr->key} — {$attr->description}");
                    }
                }
            }
        });

        /** @var array<string, string> $configScopes */
        $configScopes = config('developer.scopes', []);
        $scopes = array_merge($scopes, $configScopes);

        $this->writeCache($scopes);
        $this->populateRegistry($context, $scopes);

        $count = count($scopes);

        $context->set('scopes.count', $count);
        $context->set('scopes.map', $scopes);

        return CompilerResult::success(
            message: "Discovered {$count} OAuth scopes",
            metrics: ['scopes' => $count],
        );
    }

    /**
     * {@inheritDoc}
     */
    public function name(): string
    {
        return 'Scope Registry';
    }

    /**
     * Write the scope map to the cache file.
     *
     * Generates a PHP file that returns the scope array when included.
     * The file is stored in the bootstrap/cache directory alongside
     * other compiled framework artifacts.
     *
     * @param  array<string, string>  $scopes  The scope key-to-description map.
     * @return void
     */
    private function writeCache(array $scopes): void
    {
        $cachePath = base_path(self::CACHE_PATH);
        $exported = var_export($scopes, true);

        $content = <<<PHP
        <?php

        declare(strict_types=1);

        /**
         * Compiled OAuth Scope Registry.
         *
         * Auto-generated by ScopeRegistryCompiler. Do not edit manually.
         * Re-generate by running: php artisan di:compile
         */

        return {$exported};

        PHP;

        file_put_contents($cachePath, $content);
    }

    /**
     * Populate the ScopeRegistry instance in the container.
     *
     * Resolves the ScopeRegistry from the container and registers
     * all discovered scopes for immediate availability during the
     * remainder of the compilation process.
     *
     * @param  CompilerContext  $context  The compiler context with container access.
     * @param  array<string, string>  $scopes  The scope key-to-description map.
     * @return void
     */
    private function populateRegistry(CompilerContext $context, array $scopes): void
    {
        /** @var ScopeRegistry $registry */
        $registry = $context->container->make(ScopeRegistry::class);

        foreach ($scopes as $key => $description) {
            $registry->register($key, $description);
        }
    }
}
